Repository eygraber/JsonPathKt, pull requests merged in 2023-10, with the labels that each got.

#15 Fix maven coordinates
  README.md
Labels: documentation

#25 Update Kotlin to 1.9.20
  gradle/libs.versions.toml
  jsonpath-benchmarks/build.gradle.kts
  jsonpath-core/build.gradle.kts
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/PathCompiler.kt
  jsonpath-kotlinx/build.gradle.kts
  jsonpath-test/build.gradle.kts
  settings.gradle.kts
Labels: enhancement

#27 Fix the PathCompiler missing certain wildcard paths
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/PathCompiler.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/PathCompilerTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/path/WildcardTest.kt
Labels: bug

#28 Make wildcard tokens into data objects
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/PathCompiler.kt
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/tokens/DeepScanWildcardToken.kt
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/tokens/WildcardToken.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/PathCompilerTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/ArrayAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/ArrayLengthBasedRangeAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/DeepScanArrayAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/DeepScanLengthBasedArrayAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/DeepScanObjectAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/DeepScanWildcardTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/MultiArrayAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/ObjectAccessorTokenTest.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/tokens/WildcardTokenTest.kt
Labels: enhancement
