Repository eygraber/JsonPathKt, pull requests merged in 2023-11, with the labels that each got.

#30 Add Option to Return Single Values Wrapped in an Array
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/JsonPath.kt
  jsonpath-core/src/commonMain/kotlin/com/nfeld/jsonpathkt/ResolutionOptions.kt
  jsonpath-core/src/commonTest/kotlin/com/nfeld/jsonpathkt/path/WrapSingleValueTest.kt
  jsonpath-jsonjava/src/main/kotlin/com/nfeld/jsonpathkt/jsonjava/JsonJavaResolution.kt
  jsonpath-kotlinx/src/commonMain/kotlin/com/nfeld/jsonpathkt/kotlinx/KotlinxResolution.kt
Labels: enhancement

#33 Update the POM dev
  gradle.properties
Labels: chore

#43 Don't use browser with js target
  jsonpath-core/build.gradle.kts
  jsonpath-kotlinx/build.gradle.kts
  jsonpath-test/build.gradle.kts
Labels: gradle
